// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Adicionando logs para depuração
console.log('Supabase URL from .env:', SUPABASE_URL);
console.log('Supabase Publishable Key from .env:', SUPABASE_PUBLISHABLE_KEY);

// Validação explícita da URL antes de criar o cliente Supabase
const isValidUrl = (url: string | undefined): boolean => {
  if (!url) return false;
  try {
    const parsedUrl = new URL(url);
    return parsedUrl.protocol === 'http:' || parsedUrl.protocol === 'https:';
  } catch (e) {
    return false;
  }
};

if (!isValidUrl(SUPABASE_URL)) {
  console.error('ERRO CRÍTICO: VITE_SUPABASE_URL não é uma URL HTTP/HTTPS válida. Por favor, verifique seu arquivo .env.');
  // Para evitar que o aplicativo trave, você pode retornar um cliente dummy ou lançar um erro.
  // Por enquanto, vamos lançar um erro para que o problema seja visível.
  throw new Error('Configuração inválida: VITE_SUPABASE_URL deve ser uma URL HTTP ou HTTPS válida.');
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error('ERRO CRÍTICO: VITE_SUPABASE_PUBLISHABLE_KEY não está definida. Por favor, verifique seu arquivo .env.');
  throw new Error('Configuração inválida: VITE_SUPABASE_PUBLISHABLE_KEY não está definida.');
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});