// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Adicionando logs para depuração
console.log('Supabase URL from .env:', SUPABASE_URL);
console.log('Supabase Publishable Key from .env:', SUPABASE_PUBLISHABLE_KEY);

// Verificação adicional para garantir que as variáveis não são undefined ou vazias
if (!SUPABASE_URL) {
  console.error('VITE_SUPABASE_URL is not defined. Please check your .env file.');
}
if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error('VITE_SUPABASE_PUBLISHABLE_KEY is not defined. Please check your .env file.');
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});